Repository openfun/joanie, pull requests merged in 2021-06, with the labels that each got.

#30 🔧(renovate) replace pyup by renovate
  .pyup.yml
  renovate.json
Labels: dependencies

#28 Refactoring models to allow simple enrollments
  CHANGELOG.md
  env.d/development/common
  src/backend/joanie/core/admin.py
  src/backend/joanie/core/api.py
  src/backend/joanie/core/enums.py
  src/backend/joanie/core/exceptions.py
  src/backend/joanie/core/factories.py
  src/backend/joanie/core/management/commands/loaddatafake.py
  src/backend/joanie/core/migrations/0001_initial.py
  src/backend/joanie/core/models.py
  src/backend/joanie/core/models/accounts.py
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/core/serializers.py
  src/backend/joanie/lms_handler/backends/dummy.py
  src/backend/joanie/lms_handler/backends/failing.py
  src/backend/joanie/lms_handler/backends/openedx.py
  src/backend/joanie/lms_handler/tests/test_backend_dummy.py
  src/backend/joanie/lms_handler/tests/test_backend_openedx.py
  src/backend/joanie/settings.py
  src/backend/joanie/tests/base.py
  src/backend/joanie/tests/test_admin_product.py
  src/backend/joanie/tests/test_api_address.py
  src/backend/joanie/tests/test_api_course.py
  src/backend/joanie/tests/test_api_enrollment.py
  src/backend/joanie/tests/test_api_order.py
  src/backend/joanie/tests/test_models_course_run.py
  src/backend/joanie/tests/test_models_enrollment.py
  src/backend/joanie/tests/test_models_order.py
  src/backend/joanie/tests/test_models_product.py
  src/backend/joanie/tests/test_products.py
  src/backend/joanie/urls.py
  src/backend/setup.cfg
Labels: improvement

#32 Generate Certificate
  CHANGELOG.md
  src/backend/joanie/core/admin.py
  src/backend/joanie/core/factories.py
  src/backend/joanie/core/migrations/0003_auto_20210607_0938.py
  src/backend/joanie/core/models/certifications.py
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/settings.py
  src/backend/joanie/tests/test_models_product.py
  src/backend/setup.cfg
Labels: feature
