Repository openfun/joanie, pull requests merged in 2022-09, with the labels that each got.

#122 ✨(badges) add Open Badge Factory provider
  CHANGELOG.md
  env.d/development/common
  src/backend/joanie/badges/exceptions.py
  src/backend/joanie/badges/providers/__init__.py
  src/backend/joanie/badges/providers/base.py
  src/backend/joanie/badges/providers/obf.py
  src/backend/joanie/settings.py
  src/backend/joanie/tests/badges/providers/__init__.py
  src/backend/joanie/tests/badges/providers/test_obf.py
  src/backend/joanie/tests/badges/test_models.py
  src/backend/setup.cfg
Labels: feature, needs review

#126 🐛(tray) specify ingress class name to use
  src/tray/templates/services/nginx/ingress.yml.j2
  src/tray/vars/all/main.yml
Labels: bug, work in progress

#138 ♻️(serializer) improve EnrollmentSerializer
  Makefile
  src/backend/joanie/core/serializers.py
  src/backend/joanie/tests/core/test_api_course.py
  src/backend/joanie/tests/core/test_api_enrollment.py
Labels: improvement
