Repository openfun/joanie, pull requests merged in 2022-07, with the labels that each got.

#105 💚(circleci) migrate to new circleci images
  .circleci/config.yml
  Dockerfile
  Makefile
Labels: dependencies

#108 ✏️(project) fix README typos
  README.md
Labels: documentation, improvement, needs review

#111 ✨(backend) add badges app with models
  CHANGELOG.md
  src/backend/joanie/badges/__init__.py
  src/backend/joanie/badges/admin.py
  src/backend/joanie/badges/apps.py
  src/backend/joanie/badges/factories.py
  src/backend/joanie/badges/migrations/0001_initial.py
  src/backend/joanie/badges/migrations/__init__.py
  src/backend/joanie/badges/models.py
  src/backend/joanie/badges/views.py
  src/backend/joanie/settings.py
  src/backend/joanie/tests/test_models_badges.py
Labels: feature, needs review

#113 👷(tray) add arnold tray to deploy joanie to kubernetes
  .circleci/config.yml
  CHANGELOG.md
  arnold.yml
  src/tray/templates/services/app/_env.yml.j2
  src/tray/templates/services/app/configs/__init__.py.j2
  src/tray/templates/services/app/configs/settings.py.j2
  src/tray/templates/services/app/deploy.yml.j2
  src/tray/templates/services/app/job_db_migrate.yml.j2
  src/tray/templates/services/app/secret.yml.j2
  src/tray/templates/services/app/svc.yml.j2
  src/tray/templates/services/nginx/configs/healthcheck.conf.j2
  src/tray/templates/services/nginx/configs/joanie.conf.j2
  src/tray/templates/services/nginx/deploy.yml.j2
  src/tray/templates/services/nginx/ingress.yml.j2
  src/tray/templates/services/nginx/secret.yml.j2
  src/tray/templates/services/nginx/static-svc.yml.j2
  src/tray/templates/services/nginx/svc.yml.j2
  src/tray/templates/services/postgresql/deploy.yml.j2
  src/tray/templates/services/postgresql/ep.yml.j2
  src/tray/templates/services/postgresql/secret.yml.j2
  src/tray/templates/services/postgresql/svc.yml.j2
  src/tray/tray.yml
  src/tray/vars/all/main.yml
  src/tray/vars/settings.yml
  src/tray/vars/vault/main.yml.j2
Labels: feature

#115 🗃️(certificate) add certificate_definition fields
  CHANGELOG.md
  docs/reference/models.md
  src/backend/joanie/core/admin.py
  src/backend/joanie/core/api.py
  src/backend/joanie/core/factories.py
  src/backend/joanie/core/migrations/0001_initial.py
  src/backend/joanie/core/models/certifications.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/test_api_certificate.py
  src/backend/joanie/tests/test_api_course.py
  src/backend/joanie/tests/test_commands_generate_certificates.py
  src/backend/joanie/tests/test_models_certificate.py
Labels: improvement

#119 💚(i18n) add internationalization jobs
  .circleci/config.yml
Labels: improvement

#120 🐛(admin) custom change form for translatable admin with actions
  src/backend/joanie/core/admin.py
  src/backend/joanie/core/templates/joanie/admin/translatable_change_form_with_actions.html
  src/backend/joanie/tests/test_admin_course.py
  src/backend/joanie/tests/test_admin_order.py
  src/backend/joanie/tests/test_admin_product.py
Labels: bug
