Repository openfun/joanie, pull requests merged in 2022-08, with the labels that each got.

#123 🔧(tray/settings) add setting for CSRF trusted origins
  src/backend/joanie/settings.py
  src/tray/templates/services/app/deploy.yml.j2
  src/tray/vars/all/main.yml
Labels: improvement

#125 🔧(tray) rename CORS_ALLOWED_ORIGINS into DJANGO_CORS_ALLOWED_ORIGINS
  src/tray/templates/services/app/deploy.yml.j2
Labels: bug

#129 ⬆️(deps) upgrade marion to version 0.4.0 and howard to version 0.3.0
  src/backend/setup.cfg
Labels: dependencies

#131 🔧(settings) make cache durations configurable
  env.d/development/common
  src/backend/joanie/settings.py
Labels: improvement

#132 🐛(env.d) fix env compatibility issue with docker compose 2.7.0
  env.d/development/common
Labels: bug

#133 🔧(settings) use french as default language for production environment
  src/backend/joanie/settings.py
Labels: FUN Team
