Repository openfun/joanie, pull requests merged in 2023-03, with the labels that each got.

#240 🚸(core) display course runs into admin course change view
  CHANGELOG.md
  src/backend/joanie/core/admin.py
Labels: improvement

#223 ✨(frontend) Create and init the next.js backoffice admin
  .DS_Store
  .circleci/config.yml
  .gitignore
  Makefile
  crowdin/config.yml
  docker-compose.yml
  joanie.iml
  src/.DS_Store
  src/backend/locale/es_ES/LC_MESSAGES/django.mo
  src/backend/locale/fr_CA/LC_MESSAGES/django.mo
  src/frontend/.DS_Store
  src/frontend/admin/.DS_Store
  src/frontend/admin/.eslintrc.json
  src/frontend/admin/i18n/frontend.json
  src/frontend/admin/i18n/locales/es-ES.json
  src/frontend/admin/i18n/locales/fr-CA.json
  src/frontend/admin/i18n/locales/fr-FR.json
  src/frontend/admin/jest.config.js
  src/frontend/admin/jest.setup.js
  src/frontend/admin/mocks/browser.ts
  src/frontend/admin/mocks/handlers/index.ts
  src/frontend/admin/mocks/index.ts
  src/frontend/admin/mocks/server.ts
  src/frontend/admin/next-env.d.ts
  src/frontend/admin/next.config.js
  src/frontend/admin/package.json
  src/frontend/admin/public/favicon.ico
  src/frontend/admin/public/mockServiceWorker.js
  src/frontend/admin/src/contexts/i18n/TranslationsProvider/TranslationContext.tsx
  src/frontend/admin/src/contexts/i18n/TranslationsProvider/TranslationsProvider.tsx
  src/frontend/admin/src/pages/_app.tsx
  src/frontend/admin/src/pages/_document.tsx
  src/frontend/admin/src/pages/index.tsx
  src/frontend/admin/src/styles/globals.scss
  src/frontend/admin/src/translations/es-ES.json
  src/frontend/admin/src/translations/fr-CA.json
  src/frontend/admin/src/translations/fr-FR.json
  src/frontend/admin/src/types/i18n/LocalesEnum.ts
  src/frontend/admin/src/types/utils.ts
  src/frontend/admin/src/utils/createEmotionCache.ts
  src/frontend/admin/tsconfig.json
  src/frontend/admin/yarn.lock
Labels: feature

#253 🔨(makefile) fix bootstrap command
  Makefile
Labels: bug
