Repository openfun/joanie, pull requests merged in 2023-02, with the labels that each got.

#198 🐛(core) fix a bug about auto enrollment on order validation
  CHANGELOG.md
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/core/test_models_order.py
Labels: bug

#189 ✨(back) add synchronization of course runs
  CHANGELOG.md
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/core/signals.py
  src/backend/joanie/core/utils/__init__.py
  src/backend/joanie/core/utils/webhooks.py
  src/backend/joanie/tests/core/test_models_course.py
  src/backend/joanie/tests/core/test_models_course_run.py
  src/backend/joanie/tests/core/test_models_product.py
  src/backend/joanie/tests/core/test_models_product_synchronize_products.py
  src/backend/joanie/tests/core/test_signals.py
  src/backend/joanie/tests/core/test_utils_webhooks_synchronize_course_runs.py
Labels: feature

#208 🗃️(CourseRun) set `is_listed` field to False by default
  CHANGELOG.md
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/tests/core/test_api_course_run.py
  src/backend/joanie/tests/core/test_api_enrollment.py
  src/backend/joanie/tests/core/test_models_enrollment.py
  src/backend/joanie/tests/core/test_models_order.py
  src/backend/joanie/tests/core/test_signals.py
Labels: improvement

#214 🐛(certificate) prevent server error when certificate is unprocessable
  CHANGELOG.md
  src/backend/joanie/core/api.py
  src/backend/joanie/core/models/certifications.py
  src/backend/joanie/tests/core/test_api_certificate.py
  src/backend/joanie/tests/core/test_models_certificate.py
Labels: bug

#217 ✨(accounts) store user.fullname into firstname field
  CHANGELOG.md
  src/backend/joanie/core/factories.py
  src/backend/joanie/core/models/accounts.py
  src/backend/joanie/tests/base.py
  src/backend/joanie/tests/core/test_models_user.py
Labels: question

#216 🐛(core) prevent to enroll on several course runs for the same course
  CHANGELOG.md
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/core/test_api_enrollment.py
  src/backend/joanie/tests/core/test_models_enrollment.py
  src/backend/joanie/tests/core/test_models_order.py
Labels: bug

#227 ✨(frontend) generated Typescript client for joanie api
  CHANGELOG.md
  docs/explanation/api-client-typescript.md
  src/openApiClientJs/package.json
  src/openApiClientJs/scripts/openapi-typescript-codegen/generate_api_client_local.sh
  src/openApiClientJs/yarn.lock
Labels: feature

#199 🔥(badges) remove providers
  CHANGELOG.md
  src/backend/joanie/badges/providers/__init__.py
  src/backend/joanie/badges/providers/base.py
  src/backend/joanie/badges/providers/obf.py
  src/backend/joanie/tests/badges/providers/__init__.py
  src/backend/joanie/tests/badges/providers/test_obf.py
  src/backend/setup.cfg
Labels: easy pick, needs review

#226 💬(mail) use user fullname instead of username when exists
  CHANGELOG.md
  src/backend/joanie/core/views.py
  src/backend/joanie/payment/backends/base.py
  src/backend/joanie/tests/payment/test_backend_base.py
  src/mail/mjml/order_validated.mjml
Labels: improvement

#232 🚨(tray) avoid using punctuation with password lookup
  src/tray/vars/vault/main.yml.j2
Labels: bug
