Repository openfun/joanie, pull requests merged in 2023-10, with the labels that each got.

#425 ✨(api) add list of related orders to enrollments API payload
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_enrollment.py
Labels: feature

#422 🐛(models) fix auto enrollment with closed and specific course runs
  CHANGELOG.md
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/core/test_api_enrollment.py
  src/backend/joanie/tests/core/test_models_enrollment.py
  src/backend/joanie/tests/core/test_models_order.py
  src/backend/joanie/tests/core/test_models_order_enroll_user_to_course_run.py
Labels: bug

#433 🐛(backend) fix contract definition admin view
  src/backend/joanie/core/admin.py
Labels: bug

#436 🔧(Makefile) fix help command
  Makefile
Labels: bug

#437 ✨(api) allow to send blank description/instructions field
  src/backend/joanie/core/serializers/admin.py
  src/backend/joanie/tests/core/test_api_admin_products.py
Labels: bug

#434 ✨(lms) create missing courses automatically on course run sync
  CHANGELOG.md
  src/backend/joanie/lms_handler/api.py
  src/backend/joanie/tests/lms_handler/test_api_course_run_sync_edx.py
Labels: improvement

#435 Add filter on order endpoint
  CHANGELOG.md
  src/backend/joanie/core/filters/client.py
  src/backend/joanie/tests/core/test_api_order.py
Labels: feature

#441 ✨(backend) Order and Product serializer return Contract and ContractDefinition objects
  CHANGELOG.md
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_contract.py
  src/backend/joanie/tests/core/test_api_course_product_relations.py
  src/backend/joanie/tests/core/test_api_enrollment.py
Labels: feature

#414 ✨(backend) add admin route for OrderGroups
  CHANGELOG.md
  src/backend/joanie/core/api/admin.py
  src/backend/joanie/core/serializers/admin.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_admin_order_group.py
  src/backend/joanie/tests/core/test_api_admin_products.py
  src/backend/joanie/tests/core/test_api_course_product_relations.py
  src/backend/joanie/urls.py
Labels: feature

#420 ✨(api) allow leaving organization empty on draft order
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/migrations/0015_alter_order_organization_and_more.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/core/test_api_order.py
  src/backend/joanie/tests/core/test_models_order.py
Labels: feature
