Repository openfun/joanie, pull requests merged in 2023-06, with the labels that each got.

#282 ✨(core) take products in account to process course state
  CHANGELOG.md
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/core/test_api_course.py
  src/backend/joanie/tests/core/test_models_course.py
  src/backend/joanie/tests/core/test_models_product.py
Labels: improvement

#300 🔧(frontend) update next.config.js to not import all @mui modules
  src/frontend/admin/.eslintrc.json
  src/frontend/admin/next.config.js
  src/frontend/admin/src/components/presentational/breadrumbs/CustomBreadcrumbs.tsx
  src/frontend/admin/src/components/presentational/card/SimpleCard.tsx
  src/frontend/admin/src/components/presentational/dnd/DndDefaultRow.tsx
  src/frontend/admin/src/components/presentational/dnd/DndItem.tsx
  src/frontend/admin/src/components/presentational/dnd/DndList.tsx
  src/frontend/admin/src/components/presentational/dnd/StyledDndItemContainer.tsx
  src/frontend/admin/src/components/presentational/files/thumbnail/FileThumbnail.tsx
  src/frontend/admin/src/components/presentational/hook-form/RFHList.tsx
  src/frontend/admin/src/components/presentational/hook-form/RFHSortable.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFAutocomplete.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFCheckbox.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFDateTimePicker.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFMultiCheckbox.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFProvider.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFRadioGroup.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFSelect.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFSwitch.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFTextField.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFUpload.tsx
  src/frontend/admin/src/components/presentational/inputs/select/ControlledSelect.tsx
  src/frontend/admin/src/components/presentational/link/CustomLink.tsx
  src/frontend/admin/src/components/presentational/menu-popover/MenuPopover.spec.tsx
  src/frontend/admin/src/components/presentational/menu-popover/MenuPopover.tsx
  src/frontend/admin/src/components/presentational/modal/AlertModal.tsx
  src/frontend/admin/src/components/presentational/modal/Modal.tsx
  src/frontend/admin/src/components/presentational/table/TableComponent.tsx
  src/frontend/admin/src/components/presentational/table/TableDefaultActions.tsx
  src/frontend/admin/src/components/presentational/translatable-content/TranslatableContent.tsx
  src/frontend/admin/src/components/templates/certificates-definitions/form/CertificateDefinitionForm.tsx
  src/frontend/admin/src/components/templates/courses-runs/form/CourseRunForm.tsx
  src/frontend/admin/src/components/templates/courses-runs/list/CourseRunsListColumns.tsx
  src/frontend/admin/src/components/templates/courses/form/CourseForm.tsx
  src/frontend/admin/src/components/templates/courses/form/product-relation/CourseProductRelationForm.tsx
  src/frontend/admin/src/components/templates/organizations/form/OrganizationForm.tsx
  src/frontend/admin/src/layouts/dashboard/nav/DashboardNav.tsx
  src/frontend/admin/src/layouts/dashboard/nav/account/DashboardLayoutNavAccount.tsx
  src/frontend/admin/src/layouts/dashboard/nav/content/DashboardNavContent.tsx
  src/frontend/admin/src/layouts/dashboard/nav/header/DashboardNavHeader.tsx
  src/frontend/admin/src/layouts/dashboard/nav/item/DashboardNavItem.tsx
  src/frontend/admin/src/layouts/dashboard/nav/item/StyledItem.tsx
  src/frontend/admin/src/layouts/dashboard/nav/item/list/DasboardNavItemsList.tsx
  src/frontend/admin/src/layouts/dashboard/page/DashboardLayoutPage.tsx
  src/frontend/admin/src/pages/_app.tsx
  src/frontend/admin/src/pages/_document.tsx
  src/frontend/admin/src/pages/admin/certificates-definitions/list.tsx
  src/frontend/admin/src/pages/admin/courses-runs/list.tsx
  src/frontend/admin/src/pages/admin/courses/list.tsx
  src/frontend/admin/src/pages/admin/organizations/list.tsx
Labels: improvement

#297 🧑‍💻(backend) add command sandbox-dev
  Makefile
  src/backend/joanie/core/management/commands/loaddatafake.py
Labels: improvement

#307 ✨(backend) add api endpoint to list course product relations
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_course.py
  src/backend/joanie/tests/core/test_api_course_product_relations.py
  src/backend/joanie/tests/core/test_api_products.py
  src/backend/joanie/urls.py
Labels: feature

#311 ✨(core) add nested course api endpoint to list course runs
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/tests/core/test_api_course_run.py
  src/backend/joanie/urls.py
Labels: feature

#312 ✨(core) add `has_listed_course_runs` filter to course resource
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/filters/client.py
  src/backend/joanie/tests/core/test_api_course.py
Labels: feature

#314 🚑(backend) fix course runs api endoint with nested course
  src/backend/joanie/core/api/client.py
  src/backend/joanie/tests/core/test_api_course_run.py
Labels: bug

#306 ✨(frontend) add MUI theming stack
  src/frontend/admin/src/layouts/dashboard/DashboardLayout.tsx
  src/frontend/admin/src/layouts/dashboard/config.ts
  src/frontend/admin/src/layouts/dashboard/header/DashboardLayoutHeader.tsx
  src/frontend/admin/src/layouts/dashboard/nav/DashboardNav.tsx
  src/frontend/admin/src/pages/_app.tsx
  src/frontend/admin/src/theme/JoanieThemeProvider.tsx
  src/frontend/admin/src/theme/types.ts
Labels: improvement

#301 :sparkles: (backend) add limit to orders on a product
  CHANGELOG.md
  src/backend/joanie/core/forms.py
  src/backend/joanie/core/migrations/0005_courseproductrelation_add_max_validated_orders.py
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/core/test_api_order.py
  src/backend/joanie/tests/core/test_models_order.py
Labels: feature
