Repository openfun/joanie, pull requests merged in 2023-11, with the labels that each got.

#451 ⬆️(backend) update psycopg to version 3
  CHANGELOG.md
  src/backend/setup.cfg
Labels: dependencies

#455 🔧(backend) switch from setup.cfg to pyproject.toml
  src/backend/joanie/core/authentication.py
  src/backend/pyproject.toml
  src/backend/setup.cfg
Labels: dependencies

#458 Update nested order serializer
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_certificate.py
  src/backend/joanie/tests/core/test_api_contract.py
  src/backend/joanie/tests/core/test_api_courses_contract.py
  src/backend/joanie/tests/core/test_api_organizations_contract.py
Labels: feature

#449 ✨(frontend) add home page
  src/frontend/admin/src/components/presentational/card/LinkCard.tsx
  src/frontend/admin/src/layouts/dashboard/nav/header/DashboardNavHeader.tsx
  src/frontend/admin/src/pages/admin/index.tsx
  src/frontend/admin/src/pages/index.tsx
  src/frontend/admin/src/translations/pages/home/cardTranslations.ts
  src/frontend/admin/src/utils/pages/home/homeCardsData.tsx
  src/frontend/admin/src/utils/routes/path.ts
Labels: feature

#439 🧑‍💻(backend) dev_demo: add contract
  src/backend/joanie/core/factories.py
  src/backend/joanie/demo/management/commands/create_dev_demo.py
  src/backend/joanie/tests/demo/test_commands_create_dev_demo.py
Labels: improvement

#443 🐛(backend) allow to unroll to closed course run
  CHANGELOG.md
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/tests/core/test_models_enrollment.py
Labels: bug

#473 ✨(backend) add synchronize_course_runs management command
  CHANGELOG.md
  src/backend/joanie/core/management/commands/synchronize_course_runs.py
  src/backend/joanie/tests/core/test_commands_synchronize_course_runs.py
Labels: feature
