Repository openfun/joanie, pull requests merged in 2023-12, with the labels that each got.

#516 💚(tray) fix command starting celery app
  src/tray/vars/all/main.yml
Labels: bug

#521 🩹(backend) fix crop setting of easy thumbnail aliases
  src/backend/joanie/settings.py
  src/backend/joanie/tests/core/test_api_admin_courses.py
  src/backend/joanie/tests/core/test_api_admin_organizations.py
  src/backend/joanie/tests/core/test_api_admin_products.py
  src/backend/joanie/tests/core/test_api_organizations.py
Labels: bug

#528 ✨(backend) return contract_ids into contracts_signature_link response
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/tests/core/test_api_organizations.py
  src/backend/joanie/tests/core/test_models_organization.py
Labels: improvement

#511 ✨ (backend) - remote endpoint API Joanie for other services (token security and endpoint)
  CHANGELOG.md
  env.d/development/common.dist
  src/backend/joanie/core/api/remote_endpoints.py
  src/backend/joanie/core/permissions.py
  src/backend/joanie/core/utils/course_run.py
  src/backend/joanie/remote_endpoints_urls.py
  src/backend/joanie/settings.py
  src/backend/joanie/tests/core/api/remote_endpoints/course_run/__init__.py
  src/backend/joanie/tests/core/api/remote_endpoints/course_run/test_course_run.py
  src/backend/joanie/tests/core/test_utils_course_run.py
  src/backend/joanie/urls.py
Labels: feature

#533 🔧(Makefile) fix command name to create frontend admin .env file
  Makefile
Labels: bug
