Repository openfun/joanie, pull requests merged in 2023-01, with the labels that each got.

#179 💚(circleci) homogenize docker credential environment variable
  .circleci/config.yml
Labels: bug

#184 🐛(settings) use values.Value formats as JSON to set COURSE_WEB_HOOKS
  src/backend/joanie/core/utils.py
  src/backend/joanie/settings.py
Labels: bug

#185 🔧(Dockerfile) copy mail templates during
  .dockerignore
  Dockerfile
Labels: bug, needs review

#190 Fix/admin editable username on creation
  src/backend/joanie/core/admin.py
Labels: improvement

#192 🔧(tray) restore _env.yml.j2 file
  src/tray/templates/services/app/_env.yml.j2
Labels: bug

#193 ✨(api) add "created_on" to the enrollments API payload
  src/backend/joanie/core/serializers.py
  src/backend/joanie/tests/core/test_api_course.py
  src/backend/joanie/tests/core/test_api_enrollment.py
Labels: feature

#194 🔖(release) bump to version 1.0.0
  CHANGELOG.md
  README.md
  src/backend/setup.cfg
Labels: FUN Team
