Repository openfun/joanie, pull requests merged in 2023-08, with the labels that each got.

#383 ✨(core) allow to filter order by product type
  CHANGELOG.md
  src/backend/joanie/core/filters/client.py
  src/backend/joanie/tests/core/test_api_order.py
Labels: feature

#384 🐛(core) allow to submit a pending order
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/core/test_models_order.py
Labels: bug

#345 ✨(frontend) add user access list in CourseForm and OrgnizationForm
  .circleci/config.yml
  src/frontend/admin/mocks/handlers/courses/index.ts
  src/frontend/admin/mocks/handlers/index.ts
  src/frontend/admin/mocks/handlers/organizations/index.ts
  src/frontend/admin/mocks/handlers/users/index.ts
  src/frontend/admin/src/components/presentational/hook-form/RHFProvider.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFSearch.tsx
  src/frontend/admin/src/components/presentational/hook-form/RHFSelect.tsx
  src/frontend/admin/src/components/presentational/inputs/select/BasicSelect.spec.tsx
  src/frontend/admin/src/components/presentational/inputs/select/BasicSelect.tsx
  src/frontend/admin/src/components/presentational/loading/LoadingContent.tsx
  src/frontend/admin/src/components/presentational/table/TableComponent.tsx
  src/frontend/admin/src/components/presentational/table/TableDefaultActions.tsx
  src/frontend/admin/src/components/templates/accesses/list/AccessesList.spec.tsx
  src/frontend/admin/src/components/templates/accesses/list/AccessesList.tsx
  src/frontend/admin/src/components/templates/accesses/list/AddUserAccess.spec.tsx
  src/frontend/admin/src/components/templates/accesses/list/AddUserAccess.tsx
  src/frontend/admin/src/components/templates/accesses/list/SelectAccess.spec.tsx
  src/frontend/admin/src/components/templates/accesses/list/SelectAccess.tsx
  src/frontend/admin/src/components/templates/certificates-definitions/list/CertificatesDefinitionsList.spec.tsx
  src/frontend/admin/src/components/templates/certificates-definitions/list/CertificatesDefinitionsList.tsx
  src/frontend/admin/src/components/templates/courses-runs/list/CoursesRunsList.tsx
  src/frontend/admin/src/components/templates/courses/form/CourseForm.spec.tsx
  src/frontend/admin/src/components/templates/courses/form/CourseForm.tsx
  src/frontend/admin/src/components/templates/courses/form/translations.ts
  src/frontend/admin/src/components/templates/courses/inputs/search/CourseSearch.tsx
  src/frontend/admin/src/components/templates/courses/list/CoursesList.tsx
  src/frontend/admin/src/components/templates/organizations/form/OrganizationForm.spec.tsx
  src/frontend/admin/src/components/templates/organizations/form/OrganizationForm.tsx
  src/frontend/admin/src/components/templates/organizations/form/translations.ts
  src/frontend/admin/src/components/templates/organizations/list/OrganizationsList.tsx
  src/frontend/admin/src/components/templates/users/inputs/search/UserSearch.spec.tsx
  src/frontend/admin/src/components/templates/users/inputs/search/UserSearch.tsx
  src/frontend/admin/src/hooks/useCourses/useCourses.tsx
  src/frontend/admin/src/hooks/useOrganizations/useOrganizations.tsx
  src/frontend/admin/src/hooks/useUsers/useUsers.ts
  src/frontend/admin/src/layouts/dashboard/DashboardLayout.tsx
  src/frontend/admin/src/layouts/dashboard/header/DashboardLayoutHeader.tsx
  src/frontend/admin/src/layouts/dashboard/nav/DashboardNav.tsx
  src/frontend/admin/src/pages/admin/certificates-definitions/list.tsx
  src/frontend/admin/src/pages/admin/courses/[id]/edit.tsx
  src/frontend/admin/src/pages/admin/courses/create.tsx
  src/frontend/admin/src/pages/admin/organizations/[id]/edit.tsx
  src/frontend/admin/src/pages/admin/organizations/create.tsx
  src/frontend/admin/src/services/api/models/Accesses.ts
  src/frontend/admin/src/services/api/models/Course.ts
  src/frontend/admin/src/services/api/models/Organization.ts
  src/frontend/admin/src/services/api/models/User.ts
  src/frontend/admin/src/services/factories/accesses/index.ts
  src/frontend/admin/src/services/factories/courses/index.ts
  src/frontend/admin/src/services/factories/organizations/index.ts
  src/frontend/admin/src/services/factories/users/index.ts
  src/frontend/admin/src/services/repositories/Users/UsersRepository.ts
  src/frontend/admin/src/services/repositories/courses/CoursesRepository.ts
  src/frontend/admin/src/services/repositories/organization/OrganizationRepository.ts
  src/frontend/admin/src/styles/globals.scss
  src/frontend/admin/src/translations/common/commonTranslations.ts
Labels: feature

#375 🔨(backend) PRODUCT_CERTIFICATE in demo-dev
  CHANGELOG.md
  src/backend/joanie/core/utils/webhooks.py
  src/backend/joanie/demo/defaults.py
  src/backend/joanie/demo/management/commands/create_dev_demo.py
  src/backend/joanie/tests/demo/test_commands_create_dev_demo.py
Labels: improvement

#387 ✨(core) add languages to the CourseRun serializer
  CHANGELOG.md
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_course_run.py
  src/backend/joanie/tests/core/test_api_enrollment.py
  src/backend/joanie/tests/core/test_api_products.py
Labels: FUN Team
