Repository openfun/joanie, pull requests merged in 2023-07, with the labels that each got.

#348 🐛(core) fix wish api endpoint with course code
  src/backend/joanie/core/api/client.py
  src/backend/joanie/tests/core/test_api_course_wishes.py
Labels: bug

#352 🐛(api/client) fix has_listed_course_runs course filter
  src/backend/joanie/core/filters/client.py
  src/backend/joanie/tests/core/test_api_course.py
Labels: bug

#349 Lex persona gateway
  docs/assets/lex_persona_schema_api.png
  docs/assets/lex_persona_schema_user.png
  docs/explanation/lex-persona.md
Labels: documentation

#357 Frontend/admin/fix deps issue
  src/frontend/admin/package.json
Labels: bug, critical

#365 🐛(backend) fix admin search fields
  src/backend/joanie/core/admin.py
Labels: bug

#360 ✨(api) add related certificate products to enrollment API endpoint
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_enrollment.py
Labels: feature
