Repository openfun/joanie, pull requests merged in 2024-02, with the labels that each got.

#606 🐛(backend) fix backend moodle create_user
  src/backend/joanie/lms_handler/backends/moodle.py
  src/backend/joanie/tests/lms_handler/test_backend_moodle.py
Labels: bug

#607 🐛(backend) fix course & organization uri patterns
  src/backend/joanie/client_urls.py
  src/backend/joanie/tests/core/test_models_course_product_relation.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: bug

#608 ✨(backend) allow to filter course product relation by product type
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/filters/client.py
  src/backend/joanie/tests/core/test_api_course_product_relations.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#597 :sparkles: (backend) CRUD addresses for Organization for backoffice and admin
  CHANGELOG.md
  src/backend/joanie/admin_urls.py
  src/backend/joanie/core/admin.py
  src/backend/joanie/core/api/admin.py
  src/backend/joanie/core/serializers/admin.py
  src/backend/joanie/tests/core/test_api_admin_organization_addresses.py
  src/backend/joanie/tests/core/test_api_admin_organizations.py
  src/backend/joanie/tests/swagger/admin-swagger.json
Labels: feature

#611 🚑(backend) fix get_zip_archive api endpoint
  src/backend/joanie/core/api/client.py
Labels: bug

#605 ✨(backend) bind state field into CourseRunSerializer
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/core/serializers/admin.py
  src/backend/joanie/tests/core/test_api_admin_course_runs.py
  src/backend/joanie/tests/swagger/admin-swagger.json
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#612 :sparkles: (backend) Add new properties of Organization for serializer client API
  CHANGELOG.md
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/api/organizations/test_api_organizations_contract.py
  src/backend/joanie/tests/core/api/organizations/test_api_organizations_course_product_relations.py
  src/backend/joanie/tests/core/api/organizations/test_api_organizations_courses.py
  src/backend/joanie/tests/core/api/organizations/test_list.py
  src/backend/joanie/tests/core/api/organizations/test_retrieve.py
  src/backend/joanie/tests/core/test_api_certificate.py
  src/backend/joanie/tests/core/test_api_contract.py
  src/backend/joanie/tests/core/test_api_course_product_relations.py
  src/backend/joanie/tests/core/test_api_courses_contract.py
  src/backend/joanie/tests/core/test_api_courses_order.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#625 ✨(backend) improve NestedOrderCourseSerializer
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_courses_order.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#626 ♻️(tray) run probes in a bash process
  src/tray/vars/all/main.yml
Labels: bug

#634 Refactor/product target courses modal
  src/frontend/admin/src/components/templates/products/form/sections/target-courses/ProductTargetCourseRelationForm.tsx
  src/frontend/admin/src/components/templates/products/form/translations.ts
  src/frontend/admin/src/tests/product/product.test.e2e.ts
Labels: back-office

#640 ✨(frontend) add translation tabs in ProductFormMain
  src/frontend/admin/src/components/templates/products/form/sections/main/ProductFormMain.tsx
Labels: feature, back-office

#638 ✨(backend) add has_consent_to_terms into AdminOrderSerializer
  src/backend/joanie/core/serializers/admin.py
  src/backend/joanie/tests/core/test_api_admin_orders.py
  src/backend/joanie/tests/swagger/admin-swagger.json
Labels: feature

#639 ✨(backend) allow to filter organization through course product relation
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/filters/client.py
  src/backend/joanie/tests/core/api/organizations/test_list.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#636 🧑‍💻 Create a Debug App to preview templates (certificate, degree, contract definition, invoice)
  CHANGELOG.md
  src/backend/joanie/core/views/__init__.py
  src/backend/joanie/debug/__init__.py
  src/backend/joanie/debug/urls.py
  src/backend/joanie/debug/views.py
  src/backend/joanie/settings.py
  src/backend/joanie/tests/core/debug/__init__.py
  src/backend/joanie/tests/core/debug/test_debug_urls_template_preview.py
  src/backend/joanie/tests/testing_utils.py
  src/backend/joanie/urls.py
Labels: improvement

#641 ✨(frontend) add submit button to product form
  src/frontend/admin/src/components/templates/products/form/sections/main/ProductFormMain.tsx
  src/frontend/admin/src/components/templates/products/form/sections/main/financial/ProductFormFinancial.tsx
  src/frontend/admin/src/tests/product/product.test.e2e.ts
Labels: bug, back-office

#649 🚑️(frontend) fix product unsaved alert
  src/frontend/admin/src/components/templates/products/form/sections/main/ProductFormMain.tsx
Labels: bug, back-office

#650 ✨(back) allow to configure mongo read preferences and replicaset
  src/backend/joanie/edx_imports/edx_mongodb.py
  src/backend/joanie/settings.py
Labels: improvement

#662 ♻️(tray) rename pod name to distinguish wsgi and celery
  src/tray/templates/services/app/_deploy_base.yml.j2
Labels: improvement

#660 🐛(backend) store contract context date in isoformat
  src/backend/joanie/core/migrations/0027_alter_certificate_localized_context_and_more.py
  src/backend/joanie/core/models/certifications.py
  src/backend/joanie/core/models/contracts.py
  src/backend/joanie/core/utils/contract_definition.py
  src/backend/joanie/payment/migrations/0007_alter_invoice_localized_context.py
  src/backend/joanie/payment/models.py
  src/backend/joanie/tests/core/api/order/test_submit_for_signature.py
  src/backend/joanie/tests/core/test_models_order.py
  src/backend/joanie/tests/core/test_utils_contract_definition_generate_document_context.py
Labels: bug

#658 ✨(backend) API - Contract Download - Learner should download
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/models/contracts.py
  src/backend/joanie/tests/core/test_api_contract.py
  src/backend/joanie/tests/core/test_models_contract.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#667 :sparkles: (backend) API Client - read list - Certificate enrollments owned by user
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/tests/core/test_api_certificate.py
Labels: feature
