Repository openfun/joanie, pull requests merged in 2024-12, with the labels that each got.

#983 🌐(global) update translations
  src/backend/locale/es_ES/LC_MESSAGES/django.mo
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.mo
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.mo
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/admin/i18n/locales/es-ES.json
  src/frontend/admin/i18n/locales/fr-CA.json
  src/frontend/admin/i18n/locales/fr-FR.json
  src/frontend/admin/src/translations/es-ES.json
  src/frontend/admin/src/translations/fr-CA.json
  src/frontend/admin/src/translations/fr-FR.json
Labels: FUN Team

#988 ✨(backend) Backoffice - Filter order list view per product type
  CHANGELOG.md
  src/backend/joanie/core/filters/admin/__init__.py
  src/backend/joanie/tests/core/api/admin/orders/test_list.py
  src/backend/joanie/tests/swagger/admin-swagger.json
Labels: feature request, back-office

#985 :sparkles:(backend) Backoffice - Filter order list view per creation date
  CHANGELOG.md
  src/backend/joanie/core/filters/admin/__init__.py
  src/backend/joanie/tests/core/api/admin/orders/test_list.py
  src/backend/joanie/tests/swagger/admin-swagger.json
Labels: feature request, back-office

#989 ✨(backend) Certificate API Endpoint - sort certificates by `issued_on` date field
  CHANGELOG.md
  src/backend/joanie/core/models/certifications.py
  src/backend/joanie/tests/core/test_api_certificate.py
Labels: improvement

#996 ✨(backoffice) add template name field into ContractDefinition edit view
  CHANGELOG.md
  src/frontend/admin/src/components/templates/certificates-definitions/inputs/RHFCertificateDefinitionTemplate.tsx
  src/frontend/admin/src/components/templates/contract-definition/form/ContractDefinitionForm.tsx
  src/frontend/admin/src/components/templates/contract-definition/inputs/RHFContractDefinitionName.tsx
  src/frontend/admin/src/services/api/models/ContractDefinition.ts
  src/frontend/admin/src/services/factories/contract-definition/index.ts
  src/frontend/admin/src/services/repositories/contract-definition/ContractDefinitionRepository.ts
  src/frontend/admin/src/tests/contract-definitions/ContractDefinitionTestScenario.ts
  src/frontend/admin/src/tests/contract-definitions/contract-definition.test.e2e.ts
  src/frontend/admin/src/tests/mocks/contract-definitions/contract-definition-mocks.ts
  src/frontend/admin/src/tests/product/product.test.e2e.ts
  src/frontend/admin/src/utils/string.ts
Labels: feature, back-office
