Repository openfun/joanie, pull requests merged in 2024-11, with the labels that each got.

#960 👔(backend) ignore archived runs to process payment schedule and withdraw
  CHANGELOG.md
  src/backend/joanie/core/api/client/__init__.py
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/core/utils/course_run/__init__.py
  src/backend/joanie/core/utils/course_run/aggregate_course_runs_dates.py
  src/backend/joanie/core/utils/course_run/get_course_run_metrics.py
  src/backend/joanie/tests/core/models/order/test_schedule.py
  src/backend/joanie/tests/core/test_api_course_product_relations.py
  src/backend/joanie/tests/core/test_models_course_product_relation.py
  src/backend/joanie/tests/core/utils/course_run/test_aggregate_course_run_dates.py
  src/backend/joanie/tests/core/utils/course_run/test_get_course_run_metrics.py
  src/backend/joanie/tests/core/utils/test_contract_definition_generate_document_context.py
  src/backend/joanie/tests/core/utils/test_issuers_contract_definition_generate_document.py
Labels: improvement

#969 💄(backoffice) fix dark mode issue
  src/frontend/admin/src/components/presentational/card/SimpleCard.spec.tsx
  src/frontend/admin/src/components/presentational/card/SimpleCard.tsx
  src/frontend/admin/src/components/presentational/modal/FullScreenModal.tsx
Labels: back-office

#974 💚(circleci) count available cpu cores
  .circleci/config.yml
Labels: FUN Team

#971 ✨(backend) Authorize enrollment creation/update by admin on closed course runs
  CHANGELOG.md
  src/backend/joanie/core/api/admin/enrollment.py
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/core/serializers/admin.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_admin_enrollments.py
  src/backend/joanie/tests/core/test_models_course_run.py
  src/backend/joanie/tests/core/test_models_enrollment.py
  src/backend/joanie/tests/swagger/admin-swagger.json
Labels: feature
