Repository openfun/joanie, pull requests merged in 2024-04, with the labels that each got.

#703 ⚡️(back) improve client certificate endpoint performance
  src/backend/joanie/core/api/client/__init__.py
  src/backend/joanie/core/enums.py
  src/backend/joanie/core/filters/client/__init__.py
  src/backend/joanie/core/filters/client/certificate.py
  src/backend/joanie/tests/core/test_api_certificate.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: improvement

#723 ✨(back) add redis backend to cache configuration
  CHANGELOG.md
  src/backend/joanie/settings.py
  src/backend/pyproject.toml
Labels: feature

#694 ✨(Backend) Generate certificates from the backoffice for a course and its products relations
  CHANGELOG.md
  src/backend/joanie/core/api/admin/__init__.py
  src/backend/joanie/core/helpers.py
  src/backend/joanie/core/tasks.py
  src/backend/joanie/core/utils/course_product_relation.py
  src/backend/joanie/tests/core/api/admin/course_product_relations/test_generate_certificates.py
  src/backend/joanie/tests/core/test_utils_course_product_relation.py
  src/backend/joanie/tests/swagger/admin-swagger.json
Labels: feature

#731 🔧(backend) add missing setting to enable course runs sync
  src/backend/joanie/settings.py
Labels: bug

#725 🐛(backend) zip archive of contract by organization
  src/backend/joanie/core/api/client/__init__.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/core/utils/contract.py
  src/backend/joanie/signature/management/commands/generate_zip_archive_of_contracts.py
  src/backend/joanie/tests/core/test_api_contract.py
  src/backend/joanie/tests/core/utils/test_contract.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: bug

#733 🐛(backend) prevent to sign a document when signatories are missing
  src/backend/joanie/core/utils/contract.py
  src/backend/joanie/signature/backends/lex_persona.py
  src/backend/joanie/tests/core/utils/test_contract.py
  src/backend/joanie/tests/signature/backends/lex_persona/test_submit_for_signature.py
Labels: bug, critical

#734 ✨(back) endpoint to retrieve a course_run filter on its course_link
  CHANGELOG.md
  src/backend/joanie/edx_imports/api/__init__.py
  src/backend/joanie/edx_imports/urls.py
  src/backend/joanie/tests/edx_imports/api/test_course_run.py
  src/backend/joanie/urls.py
Labels: improvement

#739 🐛(back) exactly match resource_link when retrieving a course run
  src/backend/joanie/edx_imports/api/__init__.py
  src/backend/joanie/tests/edx_imports/api/test_course_run.py
Labels: bug

#755 🐛(edx_import) ignore conflicts when creating batch of enrollments
  CHANGELOG.md
  src/backend/joanie/edx_imports/tasks/enrollments.py
  src/backend/joanie/tests/edx_imports/test_import_enrollments.py
Labels: bug

#769 ✨(backend) Template - Update Contract Definition template with new sections (Accessibility and Required Equipment)
  CHANGELOG.md
  src/backend/joanie/core/templates/contract_definition/fragment_appendice_syllabus.html
  src/backend/joanie/core/utils/contract_context_processors.py
  src/backend/joanie/tests/core/test_utils_contract_context_processors.py
Labels: easy pick, feature
