Repository openfun/joanie, pull requests merged in 2024-05, with the labels that each got.

#774 🐛(backend) contract context for the course section data as strings (price, effort, course start, course end)
  CHANGELOG.md
  src/backend/joanie/core/templatetags/extra_tags.py
  src/backend/joanie/core/utils/contract_definition.py
  src/backend/joanie/tests/core/test_models_order.py
  src/backend/joanie/tests/core/utils/test_contract_definition_generate_document_context.py
  src/backend/joanie/tests/core/utils/test_issuers_contract_definition_generate_document.py
Labels: bug

#780 🐛(backend) manage invalid logging secret key
  CHANGELOG.md
  src/backend/joanie/core/utils/sentry.py
  src/backend/joanie/tests/core/utils/test_sentry.py
Labels: bug

#787 🐛(frontend) fix order view when organization is undefined
  CHANGELOG.md
  src/frontend/admin/src/components/templates/orders/view/OrderView.tsx
  src/frontend/admin/src/services/api/models/Order.ts
  src/frontend/admin/src/tests/orders/OrderTestScenario.ts
  src/frontend/admin/src/tests/orders/orders.test.e2e.ts
Labels: bug, back-office

#796 ✨(backend) add payment_schedule field to OrderSerializer
  CHANGELOG.md
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/api/order/test_abort.py
  src/backend/joanie/tests/core/api/order/test_create.py
  src/backend/joanie/tests/core/api/order/test_read_detail.py
  src/backend/joanie/tests/core/api/order/test_read_list.py
  src/backend/joanie/tests/core/api/order/test_update.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#794 ✨(frontend) add is graded indicator inside product detail view
  CHANGELOG.md
  src/frontend/admin/src/components/templates/products/form/sections/target-courses/ProductFormTargetCourseRow.tsx
  src/frontend/admin/src/tests/product/product.test.e2e.ts
Labels: feature, back-office

#800 🔖(minor) bump to 2.2.0
  CHANGELOG.md
  arnold.yml
  src/backend/locale/es_ES/LC_MESSAGES/django.mo
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.mo
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.mo
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/backend/pyproject.toml
  src/frontend/admin/i18n/locales/es-ES.json
  src/frontend/admin/i18n/locales/fr-CA.json
  src/frontend/admin/i18n/locales/fr-FR.json
  src/frontend/admin/package.json
  src/frontend/admin/src/translations/es-ES.json
  src/frontend/admin/src/translations/fr-CA.json
  src/frontend/admin/src/translations/fr-FR.json
  src/tray/tray.yml
  src/tray/vars/all/main.yml
Labels: FUN Team

#802 ✨(api) add `amount_currency` field to `OrderPaymentSerializer`
  CHANGELOG.md
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/api/order/test_read_detail.py
  src/backend/joanie/tests/core/test_api_course_product_relations.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: improvement

#797 ✨(backend) pay failed installment in payment schedule of an order
  CHANGELOG.md
  src/backend/joanie/core/api/client/__init__.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/payment/models.py
  src/backend/joanie/tests/core/api/order/test_submit_installment_payment.py
  src/backend/joanie/tests/core/models/order/test_schedule.py
  src/backend/joanie/tests/payment/test_models_credit_card.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#807 ✨(backend) add id field to OrderPaymentSerializer
  src/backend/joanie/core/api/client/__init__.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/api/order/test_read_detail.py
  src/backend/joanie/tests/core/test_api_course_product_relations.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: improvement

#809 ✨(backend) endpoint to tokenize a credit card with payment backend
  CHANGELOG.md
  src/backend/joanie/payment/api.py
  src/backend/joanie/payment/backends/base.py
  src/backend/joanie/payment/backends/dummy.py
  src/backend/joanie/payment/backends/lyra/__init__.py
  src/backend/joanie/tests/payment/test_api_credit_card.py
  src/backend/joanie/tests/payment/test_backend_base.py
  src/backend/joanie/tests/payment/test_backend_dummy_payment.py
  src/backend/joanie/tests/payment/test_backend_lyra.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature
