Repository openfun/joanie, pull requests merged in 2024-03, with the labels that each got.

#678 update circle-ci removed images and docker version
  .circleci/config.yml
Labels: improvement

#687 ✨(backend) bind enrollment into certificate serializer
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_certificate.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#686 🐛(backend) fix target_course_runs distinct issue
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/core/test_models_order.py
Labels: bug

#675 :sparkles: (backend) Backoffice - Cancel order
  CHANGELOG.md
  src/backend/joanie/core/api/admin.py
  src/backend/joanie/tests/core/test_api_admin_orders.py
  src/backend/joanie/tests/swagger/admin-swagger.json
Labels: feature, back-office

#698 ✨ (Backend) Backoffice - enhance exception handling to generate certificate for an order
  src/backend/joanie/core/api/admin.py
  src/backend/joanie/core/exceptions.py
  src/backend/joanie/core/helpers.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/core/test_api_admin_orders.py
  src/backend/joanie/tests/core/test_helpers.py
  src/backend/joanie/tests/core/test_models_order_get_or_generate_certificate_for_certificate_product.py
  src/backend/joanie/tests/core/test_models_order_get_or_generate_certificate_for_credential_product.py
  src/backend/joanie/tests/core/test_models_order_get_or_generate_certificate_for_enrollment_product.py
Labels: feature, improvement
