Repository openfun/joanie, pull requests merged in 2024-01, with the labels that each got.

#544 🐛(circle) fix hub-admin job
  .circleci/config.yml
Labels: bug

#545 ✨(backend) add contract_definition to product admin api
  src/backend/joanie/core/serializers/admin.py
  src/backend/joanie/tests/core/api/admin/course_product_relations/test_create.py
  src/backend/joanie/tests/core/api/admin/course_product_relations/test_list.py
  src/backend/joanie/tests/core/api/admin/course_product_relations/test_retrieve.py
  src/backend/joanie/tests/core/api/admin/course_product_relations/test_update.py
  src/backend/joanie/tests/core/test_api_admin_products.py
  src/backend/joanie/tests/swagger/admin-swagger.json
Labels: feature

#537 ✨(frontend) add country input
  src/frontend/admin/src/components/templates/organizations/form/OrganizationForm.tsx
  src/frontend/admin/src/components/templates/organizations/form/translations.ts
  src/frontend/admin/src/hooks/useOrganizations/useOrganizations.tsx
  src/frontend/admin/src/services/api/models/Organization.ts
  src/frontend/admin/src/services/factories/organizations/index.ts
  src/frontend/admin/src/services/repositories/organization/OrganizationRepository.ts
  src/frontend/admin/src/tests/mocks/organizations/organization-mock.ts
  src/frontend/admin/src/tests/organization/organization.test.e2e.ts
Labels: feature

#551 ✨(back) allow OPTIONS verb on zip-archive route testing zip creation
  src/backend/joanie/core/api/client.py
  src/backend/joanie/tests/core/test_api_contract.py
Labels: feature request

#552 ✅(frontend) fix flacky tests
  src/frontend/admin/src/components/presentational/hook-form/RHFDateTimePicker.tsx
  src/frontend/admin/src/components/templates/products/form/sections/target-courses/ProductFormTargetCourseRow.tsx
  src/frontend/admin/src/services/factories/courses/index.ts
  src/frontend/admin/src/tests/certificate-definitions/certificate-definition.test.e2e.ts
  src/frontend/admin/src/tests/course-run/course-run.test.e2e.ts
  src/frontend/admin/src/tests/product/product.test.e2e.ts
Labels: bug, back-office, Testing

#554 ✨(backend) bind children invoices to AdminInvoiceSerializer
  src/backend/joanie/core/serializers/admin.py
  src/backend/joanie/tests/core/test_api_admin_orders.py
  src/backend/joanie/tests/swagger/admin-swagger.json
Labels: improvement

#567 ✨(tray) allow to override settings
  CHANGELOG.md
  src/tray/templates/services/app/_deploy_base.yml.j2
Labels: improvement

#572 🔧(tray) fix `JOANIE_BACKOFFICE_BASE_URL` env value
  src/tray/templates/services/app/_deploy_base.yml.j2
Labels: bug

#574 🩹(backend) do not use user.last_name to create org signatory step
  src/backend/joanie/signature/backends/lex_persona.py
  src/backend/joanie/tests/signature/backends/lex_persona/test_submit_for_signature.py
Labels: bug

#581 🚑(backend) fix multiple get results in api client
  src/backend/joanie/core/api/client.py
  src/backend/joanie/tests/core/test_api_course_product_relations.py
Labels: bug, critical

#583 🔧(tray) set imagePullPolicy in admin deployment
  src/tray/templates/services/admin/deploy.yml.j2
Labels: improvement

#585 🔧(admin) update admin nginx conf to match files for dynamic routes
  docker/files/admin/etc/nginx/conf.d/default.conf
Labels: bug, back-office

#588 ✨(backend) filter contract through a course product relation id
  CHANGELOG.md
  src/backend/joanie/core/filters/client.py
  src/backend/joanie/tests/core/test_api_contract.py
  src/backend/joanie/tests/core/test_api_courses_contract.py
  src/backend/joanie/tests/core/test_api_organizations_contract.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#584 ✅(backend) fix flaky test with course run languages order
  src/backend/joanie/core/factories.py
Labels: bug

#573 ✨(backend) list users with validated orders for a course
  CHANGELOG.md
  src/backend/joanie/client_urls.py
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/filters/client.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_courses_order.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#596 ♻️(back) change default rest framework pagination class
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/pagination.py
  src/backend/joanie/settings.py
  src/backend/joanie/tests/swagger/admin-swagger.json
  src/backend/joanie/tests/swagger/swagger.json
Labels: improvement

#594 ✨(backend) allow to bulk sign contracts per course product relation
  CHANGELOG.md
  src/backend/joanie/core/api/client.py
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/tests/core/api/organizations/__init__.py
  src/backend/joanie/tests/core/api/organizations/test_api_organization_accesses.py
  src/backend/joanie/tests/core/api/organizations/test_api_organizations_contract.py
  src/backend/joanie/tests/core/api/organizations/test_api_organizations_course_product_relations.py
  src/backend/joanie/tests/core/api/organizations/test_api_organizations_courses.py
  src/backend/joanie/tests/core/api/organizations/test_contracts_signature_link.py
  src/backend/joanie/tests/core/api/organizations/test_create.py
  src/backend/joanie/tests/core/api/organizations/test_delete.py
  src/backend/joanie/tests/core/api/organizations/test_list.py
  src/backend/joanie/tests/core/api/organizations/test_retrieve.py
  src/backend/joanie/tests/core/api/organizations/test_update.py
  src/backend/joanie/tests/core/test_api_organizations.py
  src/backend/joanie/tests/core/test_models_organization.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature

#587 🧑‍💻(frontend) use dummy backend in ContractFactory
  src/backend/joanie/core/factories.py
  src/backend/joanie/tests/core/test_models_contract.py
Labels: feature

#593 :sparkles: (backend) add new properties to organization model
  CHANGELOG.md
  src/backend/joanie/core/factories.py
  src/backend/joanie/core/migrations/0023_address_organization_and_more.py
  src/backend/joanie/core/models/accounts.py
  src/backend/joanie/core/models/courses.py
  src/backend/joanie/demo/management/commands/create_dev_demo.py
  src/backend/joanie/payment/factories.py
  src/backend/joanie/tests/core/api/order/test_submit_for_signature.py
  src/backend/joanie/tests/core/test_api_address.py
  src/backend/joanie/tests/core/test_api_contract_definitions.py
  src/backend/joanie/tests/core/test_models_address.py
  src/backend/joanie/tests/core/test_models_contract.py
  src/backend/joanie/tests/core/test_models_order.py
  src/backend/joanie/tests/core/test_models_organization.py
  src/backend/joanie/tests/core/test_serializers_cached_model_serializer.py
  src/backend/joanie/tests/core/test_utils_contract_definition_generate_document_context.py
  src/backend/joanie/tests/core/test_utils_issuers_contract_definition_generate_document.py
  src/backend/joanie/tests/payment/test_backend_base.py
  src/backend/joanie/tests/swagger/admin-swagger.json
Labels: feature
