Repository openfun/joanie, pull requests merged in 2024-06, with the labels that each got.

#812 🐛 (backend) Error with payment provider are raised and not fail silently
  CHANGELOG.md
  src/backend/joanie/core/api/client/__init__.py
  src/backend/joanie/payment/backends/lyra/__init__.py
  src/backend/joanie/payment/exceptions.py
  src/backend/joanie/tests/core/api/order/test_submit_installment_payment.py
  src/backend/joanie/tests/payment/test_backend_lyra.py
  src/backend/joanie/tests/swagger/swagger.json
Labels: bug

#833 🐛(backend) moodle user creation must raise EnrollmentError exception
  CHANGELOG.md
  src/backend/joanie/lms_handler/backends/moodle.py
  src/backend/joanie/tests/core/test_flows_order.py
Labels: bug

#835 🐛(backend) fix certificate template
  CHANGELOG.md
  src/backend/joanie/core/templates/issuers/certificate.html
  src/backend/joanie/tests/core/utils/test_issuers_certificate_and_degree_generate_document.py
Labels: bug

#844 🔖(minor) bump to 2.3.0
  CHANGELOG.md
  arnold.yml
  src/backend/locale/es_ES/LC_MESSAGES/django.mo
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.mo
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.mo
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/backend/pyproject.toml
  src/frontend/admin/package.json
  src/tray/tray.yml
  src/tray/vars/all/main.yml
Labels: FUN Team

#837 ✨(backend) allow to configure how the withdrawal data is computed
  CHANGELOG.md
  src/backend/joanie/core/utils/payment_schedule.py
  src/backend/joanie/payment/__init__.py
  src/backend/joanie/settings.py
  src/backend/joanie/tests/payment/test_get_country_calendar.py
Labels: easy pick, improvement

#846 🚑(backend) fix enrollment mode update on order validation
  CHANGELOG.md
  src/backend/joanie/core/flows/order.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/core/test_flows_order.py
Labels: bug, critical

#849 🔖(minor) bump to 2.4.0
  CHANGELOG.md
  arnold.yml
  src/backend/pyproject.toml
  src/frontend/admin/package.json
  src/tray/tray.yml
  src/tray/vars/all/main.yml
Labels: FUN Team

#855 👔(backend) do not update up-to-date OpenEdX enrollment
  CHANGELOG.md
  src/backend/joanie/lms_handler/backends/openedx.py
  src/backend/joanie/tests/core/test_flows_order.py
  src/backend/joanie/tests/lms_handler/test_backend_openedx.py
Labels: improvement

#856 🔖(minor) bump to 2.5.0
  CHANGELOG.md
  arnold.yml
  src/backend/pyproject.toml
  src/frontend/admin/i18n/locales/es-ES.json
  src/frontend/admin/i18n/locales/fr-CA.json
  src/frontend/admin/i18n/locales/fr-FR.json
  src/frontend/admin/package.json
  src/frontend/admin/src/translations/es-ES.json
  src/frontend/admin/src/translations/fr-CA.json
  src/frontend/admin/src/translations/fr-FR.json
  src/mail/package.json
  src/openApiClientJs/package.json
  src/tray/tray.yml
  src/tray/vars/all/main.yml
Labels: FUN Team
