Repository openfun/joanie, pull requests merged in 2024-08, with the labels that each got.

#890 ✨(backend) sort credit card per is_main then creation date
  CHANGELOG.md
  src/backend/joanie/payment/api.py
  src/backend/joanie/tests/payment/test_api_credit_card.py
Labels: improvement

#893 🔧(tray) add cronjob for process_payment_schedule management command
  src/tray/templates/services/app/cronjob_process_payment_schedules.ym.j2
  src/tray/vars/all/main.yml
Labels: feature, improvement

#901 🔥(admin) remove has_consent_to_terms
  CHANGELOG.md
  src/frontend/admin/src/components/templates/orders/view/OrderView.tsx
  src/frontend/admin/src/components/templates/orders/view/translations.tsx
  src/frontend/admin/src/services/api/models/Order.ts
  src/frontend/admin/src/services/factories/orders/index.ts
Labels: back-office

#899 ✨(backend) allow to generate payment schedule for any kind of product
  CHANGELOG.md
  src/backend/joanie/core/flows/order.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/core/utils/payment_schedule.py
  src/backend/joanie/tests/core/api/order/test_create.py
  src/backend/joanie/tests/core/api/order/test_payment_method.py
  src/backend/joanie/tests/core/models/order/test_schedule.py
  src/backend/joanie/tests/core/test_flows_order.py
  src/backend/joanie/tests/core/test_models_order.py
Labels: feature

#904 :sparkles: (backend) prevent duplicate addresses for a user or an organization
  CHANGELOG.md
  src/backend/joanie/core/migrations/0043_address_unique_address_per_user_and_more.py
  src/backend/joanie/core/models/accounts.py
  src/backend/joanie/tests/core/api/order/test_create.py
  src/backend/joanie/tests/core/test_models_address.py
Labels: bug

#912 ✨(backend) bind payment_schedule into OrderLightSerializer
  CHANGELOG.md
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/test_api_enrollment.py
Labels: feature
