Repository openfun/joanie, pull requests merged in 2025-01, with the labels that each got.

#1004 🌐(global) update translations
  src/backend/locale/es_ES/LC_MESSAGES/django.mo
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.mo
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.mo
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/frontend/admin/i18n/locales/es-ES.json
  src/frontend/admin/i18n/locales/fr-CA.json
  src/frontend/admin/i18n/locales/fr-FR.json
  src/frontend/admin/src/translations/es-ES.json
  src/frontend/admin/src/translations/fr-CA.json
  src/frontend/admin/src/translations/fr-FR.json
Labels: FUN Team

#1010 🐛(moodle) fix `get_grades` method
  CHANGELOG.md
  src/backend/joanie/lms_handler/backends/moodle.py
  src/backend/joanie/tests/core/test_commands_generate_certificates.py
Labels: bug

#1014 🔖(chore) bump to 2.13.0
  CHANGELOG.md
  arnold.yml
  src/backend/locale/es_ES/LC_MESSAGES/django.mo
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.mo
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.mo
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/backend/pyproject.toml
  src/frontend/admin/package.json
  src/mail/package.json
  src/openApiClientJs/package.json
  src/tray/tray.yml
  src/tray/vars/all/main.yml
Labels: FUN Team

#1016 🐛(backoffice) fix an issue on target course creation
  CHANGELOG.md
  src/frontend/admin/src/components/templates/products/form/sections/target-courses/ProductFormTargetCoursesSection.tsx
  src/frontend/admin/src/tests/product/product.test.e2e.ts
Labels: bug, back-office

#1015 :sparkles: (backend) Allow to create an order when one already exists but in state refunding/refunded
  CHANGELOG.md
  src/backend/joanie/core/enums.py
  src/backend/joanie/core/migrations/0052_alter_unique_constraint_order_when_canceled_or_refund.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/tests/core/api/order/test_create.py
  src/backend/joanie/tests/core/test_models_order.py
Labels: bug

#1025 🐛(backend) fix auto organization assignment to order logic
  CHANGELOG.md
  src/backend/joanie/core/api/client/__init__.py
  src/backend/joanie/tests/core/api/order/test_create.py
Labels: bug

#1027 💚(circleci) setup tests reporting
  .circleci/config.yml
Labels: FUN Team

#1026 🔧(tray) add cronjob for delete_stuck_orders management command
  src/tray/templates/services/app/cronjob_delete_stuck_orders.yml.j2
  src/tray/vars/all/main.yml
Labels: feature

#1030 🐛(backend) add missing `updated_on` field to AdminOrderLightSerializer
  CHANGELOG.md
  src/backend/joanie/core/serializers/admin.py
  src/backend/joanie/tests/core/api/admin/orders/test_list.py
  src/backend/joanie/tests/swagger/admin-swagger.json
Labels: bug

#1035 🐛(backend) manage `error` installment in logic to debit
  CHANGELOG.md
  src/backend/joanie/core/enums.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/core/tasks/payment_schedule.py
  src/backend/joanie/core/utils/payment_schedule.py
  src/backend/joanie/tests/core/test_utils_payment_schedule.py
Labels: bug
