Repository openfun/joanie, pull requests merged in 2025-02, with the labels that each got.

#1038 🔖(chore) bump to 2.14.1
  CHANGELOG.md
  arnold.yml
  src/backend/pyproject.toml
  src/frontend/admin/package.json
  src/mail/package.json
  src/openApiClientJs/package.json
  src/tray/tray.yml
  src/tray/vars/all/main.yml
Labels: FUN Team

#1042 🔧(backend) Allow to configure JOANIE_LMS_BACKENDS through env var
  CHANGELOG.md
  docs/explanation/lms-connection.md
  docs/moodle.md
  env.d/development/common.dist
  src/backend/joanie/core/utils/__init__.py
  src/backend/joanie/settings.py
  src/backend/joanie/tests/core/utils/configuration_fields/test_lms_backends_field.py
Labels: improvement

#1044 🔖(chore) bump to 2.15.0
  CHANGELOG.md
  arnold.yml
  src/backend/pyproject.toml
  src/frontend/admin/package.json
  src/mail/package.json
  src/openApiClientJs/package.json
  src/tray/tray.yml
  src/tray/vars/all/main.yml
Labels: FUN Team

#1045 🥅(backend) catch payment provider api error on credit card deletion
  CHANGELOG.md
  src/backend/joanie/payment/models.py
  src/backend/joanie/tests/payment/test_models_credit_card.py
Labels: improvement

#1051 📌(backend) pin boto3 to version less than 1.36
  renovate.json
  src/backend/pyproject.toml
Labels: bug, dependencies

#1056 🔖(chore) bump to 2.16.0
  CHANGELOG.md
  arnold.yml
  src/backend/locale/es_ES/LC_MESSAGES/django.mo
  src/backend/locale/es_ES/LC_MESSAGES/django.po
  src/backend/locale/fr_CA/LC_MESSAGES/django.mo
  src/backend/locale/fr_CA/LC_MESSAGES/django.po
  src/backend/locale/fr_FR/LC_MESSAGES/django.mo
  src/backend/locale/fr_FR/LC_MESSAGES/django.po
  src/backend/pyproject.toml
  src/frontend/admin/package.json
  src/frontend/admin/src/translations/es-ES.json
  src/frontend/admin/src/translations/fr-CA.json
  src/frontend/admin/src/translations/fr-FR.json
  src/mail/package.json
  src/openApiClientJs/package.json
  src/tray/tray.yml
  src/tray/vars/all/main.yml
Labels: FUN Team

#1032 ✨(backend) add `start` and `end` date on `OrderGroup` model
  CHANGELOG.md
  src/backend/joanie/core/admin.py
  src/backend/joanie/core/migrations/0056_alter_ordergroup_and_more.py
  src/backend/joanie/core/models/products.py
  src/backend/joanie/core/serializers/admin.py
  src/backend/joanie/core/serializers/client.py
  src/backend/joanie/tests/core/api/admin/orders/test_retrieve.py
  src/backend/joanie/tests/core/api/order/test_create.py
  src/backend/joanie/tests/core/test_api_admin_order_group.py
  src/backend/joanie/tests/core/test_api_course_product_relations.py
  src/backend/joanie/tests/core/test_models_order_group.py
  src/backend/joanie/tests/swagger/admin-swagger.json
  src/backend/joanie/tests/swagger/swagger.json
Labels: feature
